version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - lumidoc_network

networks:
  lumidoc_network:
    driver: bridge