version: '3.8'
services:


  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - lumidoc_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    ports:
      - "9200:9200"
    networks:
      - lumidoc_network

  postgres:
    image: ankane/pgvector  # ✅ Use pgvector-supported PostgreSQL
    container_name: backend-postgres
    restart: always
    environment:
      POSTGRES_USER: lumidoc_user
      POSTGRES_PASSWORD: lumidoc_pass
      POSTGRES_DB: lumidoc_db
    ports:
      - "5432:5432"
    networks:
      - lumidoc_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  lumidoc_network:
    driver: bridge

volumes:
  postgres_data: